// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-l6cHtbV2jjYrFvDjriUNjUVS4lJrZQ',
    appId: '1:757310120342:web:7761637135da4ef69f7db7',
    messagingSenderId: '757310120342',
    projectId: 'template-app-371b9',
    authDomain: 'template-app-371b9.firebaseapp.com',
    storageBucket: 'template-app-371b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCX9EpnbRGBzIdHPggmCp5yct0BXjhJhnM',
    appId: '1:757310120342:android:1bca4249c4bcea7e9f7db7',
    messagingSenderId: '757310120342',
    projectId: 'template-app-371b9',
    storageBucket: 'template-app-371b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQFp1NH77Z5IkvJZ31z1S_uH-ltwX_I7Q',
    appId: '1:757310120342:ios:efc7ddb6cb6797e49f7db7',
    messagingSenderId: '757310120342',
    projectId: 'template-app-371b9',
    storageBucket: 'template-app-371b9.appspot.com',
    iosBundleId: 'com.example.templatesFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQFp1NH77Z5IkvJZ31z1S_uH-ltwX_I7Q',
    appId: '1:757310120342:ios:747eab059e9ea7c59f7db7',
    messagingSenderId: '757310120342',
    projectId: 'template-app-371b9',
    storageBucket: 'template-app-371b9.appspot.com',
    iosBundleId: 'com.example.templatesFlutterApp.RunnerTests',
  );
}
