// Mocks generated by Mockito 5.4.4 from annotations
// in templates_flutter_app/test/unit/controllers/template_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:templates_flutter_app/services/template_data_services.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TemplateDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTemplateDataService extends _i1.Mock
    implements _i2.TemplateDataService {
  MockTemplateDataService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> getData(
    _i2.TemplateDataService? dataService,
    String? image,
    Function? setState,
    String? name,
    String? urlRepository,
    String? nameImage,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getData,
          [
            dataService,
            image,
            setState,
            name,
            urlRepository,
            nameImage,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> accessDemo(String? image) => (super.noSuchMethod(
        Invocation.method(
          #accessDemo,
          [image],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> fetchGetNameImage(String? image) => (super.noSuchMethod(
        Invocation.method(
          #fetchGetNameImage,
          [image],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> fetchDownloadImage(String? url) => (super.noSuchMethod(
        Invocation.method(
          #fetchDownloadImage,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> saveImageToGallery(_i4.File? image) => (super.noSuchMethod(
        Invocation.method(
          #saveImageToGallery,
          [image],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String?> fetchNameTemplate(String? image) => (super.noSuchMethod(
        Invocation.method(
          #fetchNameTemplate,
          [image],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<String?> fetchUrlTemplate(String? image) => (super.noSuchMethod(
        Invocation.method(
          #fetchUrlTemplate,
          [image],
        ),
        returnValue: _i3.Future<String?>.value(),
      ) as _i3.Future<String?>);

  @override
  _i3.Future<void> fetchSaveUrlTemplate(String? url) => (super.noSuchMethod(
        Invocation.method(
          #fetchSaveUrlTemplate,
          [url],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
